spring:
  application.name: congratulation-manager-bot
  profiles.active: ${ENVIRONMENT_PROFILE_NAME:dev}
  cloud:
    vault:
      host: 192.168.88.248
      port: 8200
      scheme: http
      token: ${VAULT_TOKEN}
  config.import: vault://
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-ui
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
bot:
  name: CongratulationOrganizerBot
  token: ${bot.token}