spring:
  application:
    name: congratulation-manager-bot
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-ui
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
bot:
  name: CongratulationOrganizerBot
  token: ${secret.bot.token}
